## Makefile ##



SOURCE    = test_thread
TARGET    = exe
COMPILER  = g++
CPP_FLAGS = -Wall 
CPP_FLAGS +=-std=c++11 
CPP_FLAGS += -lpthread  

all:
	-$(COMPILER) $(SOURCE).cpp -o $(TARGET) $(CPP_FLAGS)

clean:
	@echo "rm $(TARGET).o"

